"use client";

import { useEffect, useState } from "react";
import {
  ClipboardCopy,
  FileJson,
  FileText,
  PackageCheck,
  Printer,
} from "lucide-react";
import {
  PAGE_STATUS_META,
  ROLE_LABELS,
  SECTION_REVIEW_STATUS_META,
} from "@/config/labels";
import { buildContentSummary, buildHandoffExport, buildHandoffMarkdown } from "@/lib/handoff-export";
import { canExportHandoff } from "@/lib/permissions";
import { useProject } from "@/hooks/use-project";
import { selectProjectApprovals, useApprovalsStore } from "@/stores/approvals-store";
import { selectProjectComments, useCommentsStore } from "@/stores/comments-store";
import { selectProjectMembers, useMembersStore } from "@/stores/members-store";
import { useSessionStore } from "@/stores/session-store";
import { toast } from "@/stores/ui-store";
import { formatRelative } from "@/utils/dates";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";

/**
 * Development handoff: JSON export, print-friendly summary, and a copyable
 * content outline. Internal exports include labelled agency notes; customer
 * exports exclude them.
 */
export default function HandoffPage() {
  const { project, projectId } = useProject();
  const user = useSessionStore((s) => s.user);
  const loadComments = useCommentsStore((s) => s.load);
  const loadApprovals = useApprovalsStore((s) => s.load);
  const loadMembers = useMembersStore((s) => s.load);
  const comments = useCommentsStore((s) => selectProjectComments(s, projectId));
  const approvals = useApprovalsStore((s) => selectProjectApprovals(s, projectId));
  const members = useMembersStore((s) => selectProjectMembers(s, projectId));
  const [audience, setAudience] = useState<"internal" | "customer">("internal");

  useEffect(() => {
    if (!projectId) return;
    void loadComments(projectId);
    void loadApprovals(projectId);
    void loadMembers(projectId);
  }, [projectId, loadComments, loadApprovals, loadMembers]);

  if (!project) return null;

  if (!canExportHandoff(user.role)) {
    return (
      <EmptyState
        icon={PackageCheck}
        title="Handoff exports are generated by the agency"
        description="Your agency will share the approved blueprint and development handoff with you."
      />
    );
  }

  const isApproved =
    project.status === "approved" ||
    project.status === "in-development" ||
    project.status === "completed";

  const downloadJson = () => {
    const data = buildHandoffExport(project, comments, approvals, audience);
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-handoff-${audience}.json`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    toast("JSON export downloaded", "success");
  };

  const downloadMarkdown = () => {
    const data = buildHandoffExport(project, comments, approvals, audience);
    const blob = new Blob([buildHandoffMarkdown(data)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-handoff-${audience}.md`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    toast("Markdown brief downloaded", "success");
  };

  const copySummary = async () => {
    try {
      await navigator.clipboard.writeText(buildContentSummary(project));
      toast("Content summary copied", "success");
    } catch {
      toast("Could not copy to the clipboard", "error");
    }
  };

  const memberName = (id?: string) =>
    members.find((m) => m.userId === id)?.name ?? "Team member";

  const visibleComments =
    audience === "internal" ? comments : comments.filter((c) => c.visibility === "customer");

  return (
    <div className="mx-auto max-w-3xl space-y-6 print:max-w-none">
      <Card className="print:hidden">
        <CardHeader
          title={
            <span className="inline-flex items-center gap-2">
              <PackageCheck className="size-4 text-slate-400" aria-hidden />
              Development handoff
            </span>
          }
          description={
            isApproved
              ? "The blueprint is approved — generate the handoff for the development team."
              : "The blueprint isn't approved yet. You can still preview the handoff; the final export should come from the approved version."
          }
        />
        <CardBody className="space-y-4">
          <div
            className="flex rounded-lg border border-slate-200 bg-slate-50 p-0.5"
            role="group"
            aria-label="Export audience"
          >
            {(
              [
                ["internal", "Internal (with agency notes)"],
                ["customer", "Customer-facing"],
              ] as const
            ).map(([value, label]) => (
              <button
                key={value}
                type="button"
                aria-pressed={audience === value}
                onClick={() => setAudience(value)}
                className={
                  audience === value
                    ? "flex-1 cursor-pointer rounded-md bg-white px-3 py-1.5 text-xs font-medium text-indigo-700 shadow-sm"
                    : "flex-1 cursor-pointer rounded-md px-3 py-1.5 text-xs font-medium text-slate-500"
                }
              >
                {label}
              </button>
            ))}
          </div>
          <p className="text-xs text-slate-500">
            {audience === "internal"
              ? "Includes agency-only comments and internal notes, clearly labelled as internal."
              : "Excludes internal agency notes, private developer notes, and internal assignments."}
          </p>
          <div className="flex flex-wrap gap-2">
            <Button onClick={downloadMarkdown}>
              <FileText className="size-4" aria-hidden />
              Download brief (Markdown)
            </Button>
            <Button variant="outline" onClick={downloadJson}>
              <FileJson className="size-4" aria-hidden />
              Download JSON
            </Button>
            <Button variant="outline" onClick={() => window.print()}>
              <Printer className="size-4" aria-hidden />
              Print-friendly view
            </Button>
            <Button variant="outline" onClick={() => void copySummary()}>
              <ClipboardCopy className="size-4" aria-hidden />
              Copy content summary
            </Button>
          </div>
        </CardBody>
      </Card>

      {/* Printable summary */}
      <div className="space-y-6">
        <Card>
          <CardHeader
            title={`${project.name} — Blueprint handoff`}
            description={`${project.companyName} · ${project.websiteType} · Platform: ${project.questionnaire.platform}`}
            action={
              isApproved ? (
                <Badge className="border-emerald-200 bg-emerald-50 text-emerald-700">
                  Approved
                  {project.approvedAt && ` ${formatRelative(project.approvedAt)}`}
                </Badge>
              ) : undefined
            }
          />
          <CardBody className="space-y-4 text-sm">
            {project.questionnaire.brand && (
              <div className="flex items-center gap-2">
                <span className="text-xs text-slate-500">Design system:</span>
                {[
                  project.questionnaire.brand.primaryColor,
                  project.questionnaire.brand.secondaryColor,
                  project.questionnaire.brand.accentColor,
                ].map((color) => (
                  <span
                    key={color}
                    className="inline-flex items-center gap-1 text-xs text-slate-600"
                  >
                    <span
                      className="size-4 rounded-full border border-slate-200"
                      style={{ backgroundColor: color }}
                    />
                    {color}
                  </span>
                ))}
                <span className="text-xs text-slate-500">
                  · {project.questionnaire.brand.headingStyle} headings ·{" "}
                  {project.questionnaire.brand.buttonStyle} buttons
                </span>
              </div>
            )}
            {project.questionnaire.visualStyles.length > 0 && (
              <p className="text-slate-700">
                <span className="text-xs text-slate-500">Direction:</span>{" "}
                {project.questionnaire.visualStyles.join(", ")}
              </p>
            )}
            {project.approvalNote && (
              <p className="rounded-lg bg-emerald-50 px-3 py-2 text-emerald-800">
                <span className="text-xs font-medium">Approval note:</span>{" "}
                {project.approvalNote}
              </p>
            )}
          </CardBody>
        </Card>

        {/* Page-by-page */}
        {[...project.pages]
          .sort((a, b) => Number(b.isHomepage) - Number(a.isHomepage) || a.order - b.order)
          .map((page) => (
            <Card key={page.id}>
              <CardHeader
                title={`${page.name}${page.isHomepage ? " (Homepage)" : ""}`}
                description={`${page.sections.length} sections`}
                action={
                  <Badge className={PAGE_STATUS_META[page.status].badgeClass}>
                    {PAGE_STATUS_META[page.status].label}
                  </Badge>
                }
              />
              <CardBody className="divide-y divide-slate-100 p-0">
                {[...page.sections]
                  .sort((a, b) => a.order - b.order)
                  .map((section, index) => {
                    const sectionComments = visibleComments.filter(
                      (c) => c.sectionId === section.id,
                    );
                    return (
                      <div key={section.id} className="px-5 py-3 text-sm">
                        <p className="font-medium text-slate-800">
                          {index + 1}.{" "}
                          {String(section.content.heading ?? "") ||
                            SECTION_REVIEW_STATUS_META[section.reviewStatus].label}
                          <span className="ml-2 text-xs font-normal text-slate-500">
                            {section.sectionType} ·{" "}
                            {SECTION_REVIEW_STATUS_META[section.reviewStatus].label}
                          </span>
                        </p>
                        {section.notes.customerNote && (
                          <p className="mt-1 text-xs text-slate-600">
                            Customer note: {section.notes.customerNote}
                          </p>
                        )}
                        {audience === "internal" && section.notes.agencyQuestion && (
                          <p className="mt-1 text-xs text-amber-700">
                            [INTERNAL] {section.notes.agencyQuestion}
                          </p>
                        )}
                        {section.notes.imageRequirement !== "none" && (
                          <p className="mt-1 text-xs text-sky-700">
                            Imagery: {section.notes.imageRequirement.replace(/-/g, " ")}
                          </p>
                        )}
                        {sectionComments.length > 0 && (
                          <ul className="mt-1.5 space-y-1">
                            {sectionComments.map((c) => (
                              <li key={c.id} className="text-xs text-slate-600">
                                {c.visibility === "agency" && (
                                  <span className="font-medium text-amber-700">
                                    [INTERNAL]{" "}
                                  </span>
                                )}
                                💬 {c.message}
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    );
                  })}
                {page.sections.length === 0 && (
                  <p className="px-5 py-4 text-sm text-slate-500">No sections.</p>
                )}
              </CardBody>
            </Card>
          ))}

        {/* Approvals */}
        <Card>
          <CardHeader title="Approval history" />
          <CardBody className="p-0">
            {approvals.length === 0 ? (
              <p className="px-5 py-5 text-sm text-slate-500">
                No approvals recorded yet — approvals appear here as the customer signs
                off on sections, pages, and the project.
              </p>
            ) : (
              <ul className="divide-y divide-slate-100">
                {approvals.map((approval) => (
                  <li key={approval.id} className="px-5 py-3 text-sm">
                    <span className="font-medium text-slate-800 capitalize">
                      {approval.scope}
                    </span>{" "}
                    approved by {memberName(approval.approvedById)}{" "}
                    {formatRelative(approval.approvedAt)}
                    {approval.note && (
                      <span className="text-slate-500"> — {approval.note}</span>
                    )}
                    {approval.revokedAt && (
                      <span className="ml-2 text-xs text-rose-600">
                        Revoked {formatRelative(approval.revokedAt)}: {approval.revokeReason}
                      </span>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </CardBody>
        </Card>

        {/* Team */}
        <Card className="print:hidden">
          <CardHeader title="Project team" />
          <CardBody className="p-0">
            <ul className="divide-y divide-slate-100">
              {members.map((m) => (
                <li key={m.id} className="flex items-center gap-3 px-5 py-2.5 text-sm">
                  <span className="min-w-0 flex-1 text-slate-800">{m.name}</span>
                  <span className="text-xs text-slate-500">{ROLE_LABELS[m.role]}</span>
                </li>
              ))}
            </ul>
          </CardBody>
        </Card>
      </div>
    </div>
  );
}
